### ISSUE TITLE
Produced image/snap doesn't show replies, RT's and likes... instead shows "Read 10.1k replies"

### ISSUE THREAD

**Issue by Zcehtro** [privatenumber/snap-tweet#21]
## Bug description

  What did you do? (Provide code in next section)
Took a snap of a tweet of one of the built-in examples. @jack's tweet #20.

  What did you expect to happen?
For the snap to appear as in the READ.ME on the git page.

  What happened instead?
The program executes correctly on the CLI.
But, in the produced snap, instead of there showing an <hr> separator and then the replies, rt's and likes.. there's a button that says Read XX replies.

  Do you have an error stack-trace?
Don't know what this is, but I'll get it if it can be explained to me :)

## Reproduction

  Provide one of the following:
  1. snap-tweet https://twitter.com/jack/status/20
  2. ??
  3. Sharing snap instead:

![snap-tweet-jack-20](https://user-images.githubusercontent.com/10564090/154124148-a043117d-d302-4d55-88e0-5b6ce181da94.png)
FYI I am not logged in to twitter on the browser, but I doubt that has any effect.

## Environment

- snap-tweet version: snap-tweet/1.2.1 win32-x64 node-v16.14.0
- Operating System: Microsoft Windows 10 Home 10.0.19044 N/A Build 19044
- Node version: v16.14.0
- Package manager (npm/yarn/pnpm) and version: npm 8.5.0

**Comment by Zcehtro** [comment]
Same issue as in https://github.com/privatenumber/snap-tweet/issues/19 I suppose.

**Comment by privatenumber** [comment]
Thanks for the issue. It should work fine now:
```
npx snap-tweet https://twitter.com/jack/status/20
```
![snap-tweet-jack-20](https://user-images.githubusercontent.com/1075694/154355813-bcc9869e-9aed-4398-8309-1c5ae54fb672.png)


FYI the issue with Node v17 is also fixed if you want to go back to using it.

**Comment by Zcehtro** [comment]
The black borders are because I was opening it in irfanview.
Irfanview uses by default a black background but doesn't handle transparency well when saving new images.
I assume therefore the tweet border is transparent.

Regarding the resolution of the image, I haven't got a clue... 🤨

You know... something happened now and I can't take a snap.
I'll open a new ticket... 😶
