### ISSUE TITLE
Monitor and snap automatically 

### ISSUE THREAD

**Issue by FevLoad** [privatenumber/snap-tweet#26]
```css
## Is your feature request related to a problem?
<!-- not really just asking for automation 

  What's the motivation behind this issue?

<!-- Keep record keep an eye on accounts 
Like football players and people reaction after matches or PPV games for hilarious laughing 

  Eg. I'm frustrated when...
-->

## Describe the solution you'd like
<!-- just keep track on that user and take a picture on each new tweet automatically 

  What kind of solution would you like to see?
<!-- Script can get users profiles links from either config.json or users_list.ymal file or any file format6
  What makes it a good solution?
--> I don't know what else I could say 

## Describe alternatives you've considered
<!--
  What else did you try?
 <!-- Nothing just thanks for the hard work mate 
  Do you have a workaround?
--> didn't try anything 

## Additional context
<!--
  Anything else to share?

  Screenshots? Links?
```

**Comment by privatenumber** [comment]
I'm not sure what this means.

Can you elaborate?

**Comment by FevLoad** [comment]
> I'm not sure what this means.
> 
> Can you elaborate?

Monitor user ID / profile
And take a picture for any new tweet from them automatically and save it to certain folder with the user's name

**Comment by privatenumber** [comment]
Sorry, that's out of scope of this project.

However, you can do that yourself by writing a script that polls a user's tweets via [Twitter API](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets). 

You can either spawn `snap-tweet` as a script, or import the `TweetCamera` and use it like [this](https://github.com/privatenumber/snap-tweet/blob/b86004cde69190885847cb9dfa732f6f795e1e43/src/cli.ts#L83).
