### ISSUE TITLE
Any way to run snap-tweet in a headless environment?

### ISSUE THREAD

**Issue by jvlianodorneles** [privatenumber/snap-tweet#32]
How about to run snap-tweet in a headless environment (like a virtual machine)?

Environment:
- Fedora 36 VM
- Node version 16.15.0
- Google Chrome version 103.0.5060.114

I'm getting:
```
[snap-tweet] Error: connect ECONNREFUSED 127.0.0.1:40353
✖ connect ECONNREFUSED 127.0.0.1:40353:
  https://twitter.com/telegram/status/1507356.......
```

I know that google-chrome have some flags to run headless:
`--headless --disable-gpu`

Is there some way to do this?

**Comment by privatenumber** [comment]
snap-tweet is headless:
https://github.com/privatenumber/snap-tweet/blob/68d7fec11a8492e08bcf732d5b44bce34a349dab/src/tweet-camera.ts#L74-L77

I'm guessing your environment doesn't have Chrome installed.
