### ISSUE TITLE
Rename The File When Saving

### ISSUE THREAD

**Issue by btahir** [privatenumber/snap-tweet#41]
Hi - cool library. I was wondering if there is a way to add a flag to rename the file when we save it?

**Comment by buggsi** [comment]
Check out this fork, it has several features added, including what you asked https://github.com/buggsi/snap-tweet
Acknowledgements at the bottom of the readme file.

**Comment by btahir** [comment]
Thanks!

**Comment by buggsi** [comment]
I updated the fork with the proper modifications as done by the pull request https://github.com/privatenumber/snap-tweet/pull/38

**Comment by privatenumber** [comment]
Thanks @buggsi 

Do you have any interest in help maintaining this project (+ porting over those features)? Happy to add you as a collaborator

**Comment by buggsi** [comment]
Although I'm pretty good with JavaScript and NodeJS, I've never messed with typescript. From what I see, the project is mature enough, I don't know what else could be added to it. I've tested the extra features and they work nicely. I'll keep monitoring the project, I'd be glad to help if needed. I think @FelixDubois would be a nice addition to the collaborators.

**Comment by privatenumber** [comment]
Gotcha. Would be happy to invite @FelixDubois as well!

**Comment by FelixDubois** [comment]
I thank you for your interest, I'm a beginner in ts and I felt that my work wasn't good enougth for this project. I'm very happy that some pro's are considering my work !
