### ISSUE TITLE
Doesn't support x.com

### ISSUE THREAD

**Issue by michaelfromyeg** [privatenumber/snap-tweet#43]
## Bug description

```
snap-tweet -o ./images https://x.com/michaelfromyeg/status/1794814464916959687
[snap-tweet] Error: Invalid Tweet URL: https://x.com/michaelfromyeg/status/1794814464916959687
```

## Reproduction

Run the program on any x.com tweet URL.

## Environment

- snap-tweet version: 1.2.3
- Operating System: Windows
- Node version: v22.2.0
- Package manager (npm/yarn/pnpm) and version: npm 9.7.2

**Comment by michaelfromyeg** [comment]
Happy to try and take this one and the previous one on later today!

**Comment by privatenumber** [comment]
Go for it!

**Comment by michaelfromyeg** [comment]
PR open!

**Comment by legitleavitt** [comment]
I know this is marked as closed, but the x.com url doesn't work on my M1 mac running Sonoma. Here's the output I get:
`[snap-tweet] Error: Invalid Tweet URL: https://x.com/Brian_Sauve/status/1821543365139431924`
Replacing 'x' with 'twitter' results in normal function.
